# Generated by Django 4.2.1 on 2023-05-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'This name already exist!'}, max_length=255, unique=True)),
                ('slug', models.SlugField(error_messages={'unique': 'This slug already exist!'}, unique=True)),
            ],
            options={
                'verbose_name': 'Categorys, ',
                'verbose_name_plural': 'Categorys, ',
            },
        ),
    ]
