# Generated by Django 4.2.1 on 2023-05-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_category_options_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='awards',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pizza',
            name='branches',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pizza',
            name='customer',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pizza',
            name='stuff',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
