# Generated by Django 4.2.1 on 2023-05-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_pizza_awards_pizza_branches_pizza_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branches', models.PositiveIntegerField(default=1)),
                ('awards', models.PositiveIntegerField(default=1)),
                ('customer', models.PositiveIntegerField(default=1)),
                ('stuff', models.PositiveIntegerField(default=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PizzaNumbers',
                'verbose_name_plural': 'PizzaNumbers',
            },
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='branches',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='stuff',
        ),
    ]
