# Generated by Django 4.2.1 on 2023-05-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_pizzanumbers_remove_pizza_awards_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzanumbers',
            old_name='stuff',
            new_name='staff',
        ),
    ]
