# Generated by Django 4.2.1 on 2023-05-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_rename_stuff_pizzanumbers_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzanumbers',
            options={'verbose_name': 'Pizza Number', 'verbose_name_plural': 'Pizza Number'},
        ),
    ]
