# Generated by Django 4.2.1 on 2023-06-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_pizzanumbers_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('specialist', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('profile_image', models.ImageField(upload_to='chef/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chef',
                'verbose_name_plural': 'Chef',
            },
        ),
    ]
